version: '2'

services:
  app:
    image: celery-exporter:3
    build:
      context: .
      dockerfile: Dockerfile-celery3
    user: "65534"
    volumes:
      - ./:/app
    entrypoint: celery -A celeryapp worker

  exporter:
    image: celery-exporter:3
    build:
      context: .
      dockerfile: Dockerfile-celery3
    volumes:
      - ./:/app
    ports:
      - 8888:8888

  cache:
    image: redis:alpine
